# @package _global_
repetition: 0

dataset:
  path: ../datasets/32x64/
  batch_size: 128

cross_modality:
  n_epochs: 1

mod_0_to_1:
  learning_rate: 1e-3

mod_1_to_0:
  learning_rate: 1e-3
  n_epochs: 1

autoencoder:
  learning_rate: 5e-4
  n_epochs: 1

jointencoder:
  learning_rate: 5e-4
  n_epochs: 1
  pre_reconstruction_0_size: ${layer_sizes.pre_encoding_size}

readout:
  n_epochs: 1
  learning_rate: 1e-3
